services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: cinemergence
      POSTGRES_PASSWORD: cinemergence
      POSTGRES_DB: cinemergence
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
